version: "3"

networks:
  election:

services:
  app:
    build:
      context: ./docker
    ports:
      #- "80:80"
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - election

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data3:/var/lib/mysql
      #- ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

    networks:
      - election

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: "notSecureChangeMe"

    networks:
      - election

volumes:
  mysql_data3:
  phpmyadmin:
